ProyectoVentaMusical/Areas/Admin/Controllers/AlbumesController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Data;
using Models.ViewModels;
using NuGet.ProjectModel;

namespace ProyectoVentaMusical.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AlbumesController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;

        private readonly ApplicationDbContext _context;

        public AlbumesController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            AlbumesVM albumVM = new AlbumesVM()
            {
                Album = new Albumes(),
                ListaArtistas = _context.Artistas.ToList()
            };
            return View(albumVM);
        }

        [HttpGet]
        public IActionResult Create()
        {
            AlbumesVM albumVM = new AlbumesVM()
            {
                Album = new Albumes(),
                ListaArtistas = _context.Artistas.ToList()
            };
            return View(albumVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Albumes album)
        {
            //if (ModelState.IsValid)
            //{
            string rutaPrincipal = _hostingEnvironment.WebRootPath;
            var archivos = HttpContext.Request.Form.Files;
            if (album.CodigoAlbum == 0 && archivos.Count() > 0)
            {
                //Nuevo articulo
                string nombreArchivo = Guid.NewGuid().ToString();
                var subidas = Path.Combine(rutaPrincipal, @"imagenes\albumes");
                var extension = Path.GetExtension(archivos[0].FileName);

                using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                {
                    archivos[0].CopyTo(fileStreams);
                }

                album.ImagenAlbum = @"\imagenes\albumes\" + nombreArchivo + extension;

                _context.Albumes.Add(album);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
                //}
                //else
                //{
                //    ModelState.AddModelError("Imagen", "Debes seleccionar una imagen");
                //}

            }
            return View(album);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            AlbumesVM albumVM = new AlbumesVM()
            {
                Album = _context.Albumes.FirstOrDefault(a => a.CodigoAlbum == id),
                ListaArtistas = _context.Artistas.ToList()
            };
            
            return View(albumVM);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Albumes album)
    {
        //if (ModelState.IsValid)
        //{
        string rutaPrincipal = _hostingEnvironment.WebRootPath;
        var archivos = HttpContext.Request.Form.Files;

        var articuloDesdeBd = _context.Albumes.FirstOrDefault(a => a.CodigoAlbum == album.CodigoAlbum);


        if (archivos.Count() > 0)
        {
            //Nuevo imagen para el artículo
            string nombreArchivo = Guid.NewGuid().ToString();
            var subidas = Path.Combine(rutaPrincipal, @"imagenes\albumes");
            var extension = Path.GetExtension(archivos[0].FileName);
            var nuevaExtension = Path.GetExtension(archivos[0].FileName);

            var rutaImagen = Path.Combine(rutaPrincipal, articuloDesdeBd.ImagenAlbum.TrimStart('\\'));

            if (System.IO.File.Exists(rutaImagen))
            {
                System.IO.File.Delete(rutaImagen);
            }

            //Nuevamente subimos el archivo
            using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
            {
                archivos[0].CopyTo(fileStreams);
            }

            album.ImagenAlbum = @"\imagenes\albumes\" + nombreArchivo + extension;


            articuloDesdeBd.CodigoArtista = album.CodigoArtista;
            articuloDesdeBd.NombreAlbum = album.NombreAlbum;
            articuloDesdeBd.AñoLanzamiento = album.AñoLanzamiento;
            articuloDesdeBd.ImagenAlbum = album.ImagenAlbum;
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        else
        {
            //Aquí sería cuando la imagen ya existe y se conserva
            album.ImagenAlbum = articuloDesdeBd.ImagenAlbum;
        }

        articuloDesdeBd.CodigoArtista = album.CodigoArtista;
        articuloDesdeBd.NombreAlbum = album.NombreAlbum;
        articuloDesdeBd.AñoLanzamiento = album.AñoLanzamiento;
        articuloDesdeBd.ImagenAlbum = album.ImagenAlbum;
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));

        //}
    }

    #region Llamadas a la API
    [HttpGet]
    public IActionResult GetAll()
    {
        var albumes = _context.Albumes.ToList();
        return Json(new { data = albumes });
    }

    [HttpDelete]
    public IActionResult Delete(int id)
    {
        var objFromDb = _context.Albumes.Find(id);
        if (objFromDb == null)
        {
            return Json(new { success = false, message = "Error borrando un album" });
        }
        _context.Albumes.Remove(objFromDb);
        _context.SaveChanges();
        return Json(new { success = true, message = "Album Borrado Correctamente" });
    }
    #endregion
}
}

ProyectoVentaMusical/Areas/Admin/Controllers/ComprarController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Models;
using Models.Data;
using Models.ViewModels;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ProyectoVentaMusical.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ComprarController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ComprarController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string objBuscar)
        {

            var canciones = from c in _context.Canciones select c;
            if (!string.IsNullOrEmpty(objBuscar))
            {
                canciones = canciones.Where(c => c.NombreCancion.Contains(objBuscar));
            }

            var lstFiltrada = await canciones.ToListAsync();
            CarritoVM viewModel = new CarritoVM
            {
                ListaCanciones = lstFiltrada,
                CarritoCompras = new CarritoCompras()
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> anadirACarrito(CarritoVM carritoVM)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var usuario = await _userManager.FindByIdAsync(userId);

            if (usuario == null)
            {
                return NotFound("Usuario no encontrado.");
            }

            // Verifica si ya existe un carrito para este usuario
            var carritoExistente = _context.CarritoCompras
                                           .FirstOrDefault(c => c.IdUsuario == usuario.Id);

            if (carritoExistente == null)
            {
                // Crea un nuevo carrito si no existe
                CarritoCompras nuevoCarrito = new CarritoCompras
                {
                    IdUsuario = usuario.Id,
                    NombreUsuario = usuario.UserName,
                    FechaCompra = DateTime.Now,
                    TipoPago = "Tarjeta de Crédito", //carritoVM.CarritoCompras.TipoPago,
                    Subtotal = 0,
                    Total = 0
                };

                _context.CarritoCompras.Add(nuevoCarrito);
                await _context.SaveChangesAsync();
                carritoExistente = nuevoCarrito;
            }

            // Agrega un nuevo detalle de carrito
            DetalleCarrito nuevoDetalle = new DetalleCarrito
            {
                IdCarrito = carritoExistente.IdCarrito,
                CodigoCancion = carritoVM.Cancion.CodigoCancion,
                Cantidad = carritoVM.Cancion.CantidadDisponible,
                PrecioUnitario = carritoVM.Cancion.Precio,
                Total = carritoVM.Cancion.CantidadDisponible * carritoVM.Cancion.Precio
            };

            _context.DetalleCarrito.Add(nuevoDetalle);

            // Actualiza los totales del carrito
            carritoExistente.Subtotal += nuevoDetalle.Total;
            carritoExistente.Total += nuevoDetalle.Total;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<IActionResult> CarritoCompras()
        {
            var userId = _userManager.GetUserId(User);

            // Encontrar el carrito de compras para el usuario logueado

            var carrito = _context.CarritoCompras.FirstOrDefault(c => c.IdUsuario == userId);

            if (carrito == null)
            {
                ViewBag.Message = "Debes ingresar canciones a tu carrito de compras.";
                return View();
            }

            var detalles = _context.DetalleCarrito
                .Include(dc => dc.CodigoCancionNavigation)
                .Where(dc => dc.IdCarrito == carrito.IdCarrito)
                .ToList();

            var canciones = detalles.Select(dc => dc.CodigoCancionNavigation).Distinct().ToList();

            var viewModel = new CarritoMostrarVM
            {
                CarritoCompras = carrito,
                DetalleCarrito = detalles,
                ListaCanciones = canciones
            };


            return View(viewModel);

        }


        //[HttpPost]
        //public async Task<IActionResult> CarritoCompras(int opcion)
        //{

        //    return View();
        //}

        [HttpGet]
        public async Task<IActionResult> Pagar()
        {
            var userId = _userManager.GetUserId(User);
            var user = await _userManager.FindByIdAsync(userId);

            //Encontrar la venta para el usuario logueado

            var venta = _context.Ventas.FirstOrDefault(v => v.IdUsuario == userId);

            if (venta == null)
            {
                ViewBag.Message = "Debes ingresar carritos de compra a tu venta";
                return View();
            }

            var detalles = _context.DetalleVentas
                .Include(dv => dv.CodigoCancionNavigation)
                .Where(dv => dv.IdVenta == venta.IdVenta)
                .ToList();

            var canciones = detalles.Select(dv => dv.CodigoCancionNavigation).Distinct().ToList();

            var viewModel = new VentaMostrarVM
            {
                VENTAS = venta,
                DetalleVentas = detalles,
                ListaCanciones = canciones
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ProcesarPago(VentaMostrarVM ventaVM)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var usuario = await _userManager.FindByIdAsync(userId);

            if (usuario == null)
            {
                return NotFound("Usuario no encontrado.");
            }

            var carritoCompras = await _context.CarritoCompras
                .FirstOrDefaultAsync(c => c.IdUsuario == usuario.Id);

            if (carritoCompras == null)
            {
                return BadRequest("El carrito de compras está vacío.");
            }

            List<DetalleCarrito> LstDetalleCarritos = await _context.DetalleCarrito
                .Where(d => d.IdCarrito == carritoCompras.IdCarrito)
                .ToListAsync();

            if (LstDetalleCarritos.Count == 0)
            {
                return BadRequest("No hay productos en el carrito.");
            }

            using (var transaction = await _context.Database.BeginTransactionAsync())
            {
                try
                {
                    // Crear nueva venta
                    var ventaNueva = new Ventas()
                    {
                        IdUsuario = userId,
                        FechaCompra = DateTime.Now,
                        TipoPago = ventaVM.VENTAS.TipoPago,
                        Subtotal = carritoCompras.Subtotal,
                        Total = carritoCompras.Total
                    };

                    await _context.Ventas.AddAsync(ventaNueva);
                    await _context.SaveChangesAsync(); // Guardar la venta primero para obtener el IdVenta

                    // Crear lista de detalles de venta
                    var listaDetalleVentas = new List<DetalleVentas>();

                    foreach (var item in LstDetalleCarritos)
                    {
                        listaDetalleVentas.Add(new DetalleVentas()
                        {
                            IdVenta = ventaNueva.IdVenta,
                            CodigoCancion = item.CodigoCancion,
                            Cantidad = item.Cantidad,
                            PrecioUnitario = item.PrecioUnitario,
                            Total = item.Total
                        });
                    }

                    // Guardar todos de una vez
                    await _context.DetalleVentas.AddRangeAsync(listaDetalleVentas);
                    await _context.SaveChangesAsync();

                    // Si todo fue exitoso, confirmar la transacción y enviar json
                    await transaction.CommitAsync();

                    _context.RemoveRange(LstDetalleCarritos);
                    await _context.SaveChangesAsync();

                    _context.Remove(carritoCompras);
                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Pago Procesado con Éxito" });
                }
                catch (Exception ex)
                {
                    // Si hay un error, revertir la transacción
                    await transaction.RollbackAsync();
                    //return StatusCode(500, "Ocurrió un error al procesar el pago: " + ex.Message);
                    return Json(new { success = false, message = "Error al procesar el pago: " + ex.Message });
                }
            }
            //return RedirectToAction(nameof(Index));
        }

    }
}

ProyectoVentaMusical/Views/Shared/_Layout.cshtml
@using Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoVentaMusical</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="~/ProyectoVentaMusical.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-2 border-primary shadow-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoVentaMusical</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Desplegable de Opciones
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Artistas" asp-action="Index">Artistas</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Canciones" asp-action="Index">Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Comprar" asp-action="CarritoCompras">carrito Compras</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Generos" asp-action="Index">Generos Musicales</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Albumes" asp-action="Index">Albumes</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Comprar" asp-action="Index">Comprar Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Venta de Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Historial de compras</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(CNT.Contador))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Desplegable de Opciones
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Artistas" asp-action="Index">Artistas</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Canciones" asp-action="Index">Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Comprar" asp-action="CarritoCompras">carrito Compras</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Generos" asp-action="Index">Generos Musicales</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Albumes" asp-action="Index">Albumes</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Comprar" asp-action="Index">Comprar Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Venta de Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Historial de compras</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(CNT.Usuario))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Desplegable de Opciones
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Artistas" asp-action="Index">Artistas</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Canciones" asp-action="Index">Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Comprar" asp-action="CarritoCompras">carrito Compras</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Generos" asp-action="Index">Generos Musicales</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Albumes" asp-action="Index">Albumes</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Comprar" asp-action="Index">Comprar Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Venta de Canciones</a>
                                    <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Historial de compras</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2025 - ProyectoVentaMusical - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <!-- Incluye el JavaScript de Bootstrap y sus dependencias -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- jQuery (necesario para DataTables) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

    <!-- DataTables CSS (para el diseño) -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

   

</body>
</html>